server:
   port: 8080

spring:
  application:
   name: API_GATEWAY
  cloud:
    gateway:
     routes:
     #Route Mapping
     - id: Survey_UserService       				#RouteIdentifier
       uri: http://localhost:8001/
        lb://Survey_UserService				
       predicates:
       - Path=/Survey/user /**
  
       #Route Mapping
     - id: Feedback
       uri: http://localhost:8002/
        lb://Feedback
       predicates:
     - Path=/feedback/**